version: '3'

services:
  calendar_app:
    container_name: calendar-app
    image: calendar-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
